06-20-2023 13:20:05 INFO     [main.py:19] App started
06-20-2023 13:20:19 ERROR    [login.py:31] [Employee]: Invalid Username or password with email:kelly_kapoor@gmail.com and password:Abcdef@2
06-20-2023 13:20:36 DEBUG    [employeedao.py:31] <class 'str'>: 1
06-20-2023 13:20:36 INFO     [login.py:27] Employee with e_id:Nmmm8, name:Kelly Kapoor logged in
06-20-2023 13:20:36 INFO     [main_menu.py:43] Employee e_id:Nmmm8 and designation:helpdesk logged in
06-23-2023 13:23:14 INFO     [main.py:19] App started
06-23-2023 13:23:29 DEBUG    [employeedao.py:31] <class 'str'>: 1
06-23-2023 13:23:29 INFO     [login.py:27] Employee with e_id:Nmmm8, name:Kelly Kapoor logged in
06-23-2023 13:23:29 INFO     [main_menu.py:43] Employee e_id:Nmmm8 and designation:helpdesk logged in
06-23-2023 13:23:41 INFO     [helpdesk_ticket_section.py:50] ticket_id:CXjbe is closed by Nmmm8
06-24-2023 13:24:27 DEBUG    [helpdesk_ticket_section.py:133] Closing ticket with t_id CXjbe
06-30-2023 13:30:32 INFO     [main.py:19] App started
06-30-2023 13:30:51 DEBUG    [employeedao.py:31] <class 'str'>: 1
06-30-2023 13:30:51 INFO     [login.py:27] Employee with e_id:Nmmm8, name:Kelly Kapoor logged in
06-30-2023 13:30:51 INFO     [main_menu.py:43] Employee e_id:Nmmm8 and designation:helpdesk logged in
06-31-2023 13:31:02 INFO     [helpdesk_ticket_section.py:50] ticket_id:CXjbe is closed by Nmmm8
06-31-2023 13:31:42 DEBUG    [helpdesk_ticket_section.py:133] Closing ticket with t_id CXjbe
06-31-2023 13:31:42 INFO     [ticketDAO.py:78] Ticket status changed for ticket_id:CXjbe to closed
06-31-2023 13:31:42 INFO     [ticketDAO.py:74] Message from helpdesk changed for ticket_id:CXjbe to Hope your pc got fixed. Please take time to give us feedback.
06-32-2023 13:32:45 INFO     [main.py:33] App ended
06-28-2023 14:28:14 INFO     [main.py:19] App started
06-28-2023 14:28:34 INFO     [main.py:33] App ended
06-28-2023 14:28:39 INFO     [main.py:19] App started
06-29-2023 14:29:01 INFO     [main.py:19] App started
06-29-2023 14:29:42 ERROR    [login.py:31] [Employee]: Invalid Username or password with email:tanvi@gmail.com and password:tanvi1
06-30-2023 14:30:14 ERROR    [login.py:31] [Employee]: Invalid Username or password with email:kelly_kapoor@helpdesk.com and password:abcdef@2
06-30-2023 14:30:41 ERROR    [login.py:31] [Employee]: Invalid Username or password with email:kelly_kapoor@helpdesk.com and password:abcdef@2
06-31-2023 14:31:01 INFO     [login.py:27] Employee with e_id:Nmmm8, name:Kelly Kapoor logged in
06-31-2023 14:31:01 INFO     [main_menu.py:43] Employee e_id:Nmmm8 and designation:helpdesk logged in
06-32-2023 14:32:53 INFO     [helpdesk_ticket_section.py:50] ticket_id:YRcKy is closed by Nmmm8
06-33-2023 14:33:03 DEBUG    [helpdesk_ticket_section.py:133] Closing ticket with t_id YRcKy
06-33-2023 14:33:03 INFO     [ticketDAO.py:78] Ticket status changed for ticket_id:YRcKy to closed
06-33-2023 14:33:03 INFO     [ticketDAO.py:74] Message from helpdesk changed for ticket_id:YRcKy to You are only idiot
06-34-2023 14:34:14 INFO     [main.py:19] App started
06-36-2023 14:36:34 INFO     [signup.py:23] New Customer signup with name:tanvi and email:tanvi@g.com
06-37-2023 14:37:15 INFO     [login.py:53] Employee with e_id:6twZg, name:tanvi logged in
06-38-2023 14:38:10 INFO     [login.py:53] Employee with e_id:6twZg, name:tanvi logged in
06-38-2023 14:38:52 INFO     [ticketDAO.py:23] New ticket raised with ticket_id:BSECx, title:sale by customer:6twZg
06-38-2023 14:38:52 INFO     [customer.py:37] Customer:6twZg is trying to raise a ticket
06-43-2023 14:43:21 ERROR    [login.py:31] [Employee]: Invalid Username or password with email:micheal_scott@gmail.com and password:abcdef@2
06-43-2023 14:43:50 INFO     [login.py:27] Employee with e_id:AfqTX, name:Micheal Scott logged in
06-43-2023 14:43:50 INFO     [main_menu.py:43] Employee e_id:AfqTX and designation:manager logged in
06-44-2023 14:44:17 ERROR    [login.py:31] [Employee]: Invalid Username or password with email:micheal_scott@gmail.com and password:abcdef@2
06-44-2023 14:44:42 INFO     [login.py:27] Employee with e_id:AfqTX, name:Micheal Scott logged in
06-44-2023 14:44:42 INFO     [main_menu.py:43] Employee e_id:AfqTX and designation:manager logged in
06-45-2023 14:45:57 INFO     [manager_ticket_section.py:47] Manager viewed all tickets in the organization
06-46-2023 14:46:03 INFO     [manager_ticket_section.py:47] Manager viewed all tickets in the organization
06-47-2023 14:47:28 INFO     [main.py:19] App started
06-50-2023 14:50:02 INFO     [main.py:19] App started
06-51-2023 14:51:09 INFO     [signup.py:23] New Customer signup with name:Vibhuti Narayan Mishra and email:vibhuti_narayan@gmail.com
06-51-2023 14:51:52 ERROR    [login.py:56] [Customer]: Invalid Username or password with email:vibhuti_narayan@gmail.com and password:laddu12@
06-52-2023 14:52:26 ERROR    [login.py:56] [Customer]: Invalid Username or password with email:vibhuti_narayan@gmail.com and password:laddu12@
06-52-2023 14:52:48 ERROR    [login.py:56] [Customer]: Invalid Username or password with email:vibhuti_narayan@gmail.com and password:laddu12@
06-53-2023 14:53:26 INFO     [login.py:53] Employee with e_id:BQZua, name:Vibhuti Narayan Mishra logged in
06-54-2023 14:54:23 ERROR    [login.py:56] [Customer]: Invalid Username or password with email:vibhuti_narayan@gmail.com and password:laddu12@
06-55-2023 14:55:43 ERROR    [login.py:56] [Customer]: Invalid Username or password with email:vibhuti_narayan@gmail.com and password:laddu12@
06-56-2023 14:56:09 INFO     [login.py:53] Employee with e_id:BQZua, name:Vibhuti Narayan Mishra logged in
06-56-2023 14:56:29 INFO     [login.py:53] Employee with e_id:BQZua, name:Vibhuti Narayan Mishra logged in
06-57-2023 14:57:18 INFO     [main.py:33] App ended
06-31-2023 15:31:09 INFO     [main.py:19] App started
06-31-2023 15:31:27 INFO     [login.py:27] Employee with e_id:AfqTX, name:Micheal Scott logged in
06-31-2023 15:31:27 INFO     [main_menu.py:43] Employee e_id:AfqTX and designation:manager logged in
06-32-2023 15:32:22 INFO     [main.py:19] App started
06-32-2023 15:32:34 INFO     [login.py:27] Employee with e_id:AfqTX, name:Micheal Scott logged in
06-32-2023 15:32:34 INFO     [main_menu.py:43] Employee e_id:AfqTX and designation:manager logged in
06-32-2023 15:32:52 INFO     [manager_ticket_section.py:47] Manager viewed all tickets in the organization
06-34-2023 15:34:40 INFO     [main.py:19] App started
06-34-2023 15:34:54 INFO     [login.py:27] Employee with e_id:AfqTX, name:Micheal Scott logged in
06-34-2023 15:34:54 INFO     [main_menu.py:43] Employee e_id:AfqTX and designation:manager logged in
06-35-2023 15:35:22 INFO     [manager_ticket_section.py:47] Manager viewed all tickets in the organization
06-35-2023 15:35:26 INFO     [main.py:33] App ended
17-41-2023 11:41:10 INFO     [main.py:19] App started
17-41-2023 11:41:19 ERROR    [login.py:33] [Employee]: Invalid Username or password with email:j and password:a
17-41-2023 11:41:29 ERROR    [login.py:33] [Employee]: Invalid Username or password with email:nm and password:aa
17-41-2023 11:41:36 ERROR    [login.py:33] [Employee]: Invalid Username or password with email:mm and password:ss
17-41-2023 11:41:39 INFO     [main.py:33] App ended
17-42-2023 11:42:15 INFO     [main.py:19] App started
17-42-2023 11:42:37 ERROR    [login.py:45] Employee login: SQLITE_CANTOPEN
17-44-2023 11:44:08 INFO     [main.py:33] App ended
17-45-2023 11:45:05 INFO     [main.py:19] App started
17-45-2023 11:45:11 ERROR    [login.py:45] Employee login: SQLITE_CANTOPEN
17-45-2023 11:45:33 INFO     [main.py:33] App ended
17-45-2023 11:45:34 INFO     [main.py:19] App started
17-45-2023 11:45:40 ERROR    [login.py:45] Employee login: SQLITE_CANTOPEN
17-45-2023 11:45:52 INFO     [main.py:33] App ended
17-45-2023 11:45:54 INFO     [main.py:19] App started
17-46-2023 11:46:00 ERROR    [login.py:67] Customer login: SQLITE_CANTOPEN
17-46-2023 11:46:13 INFO     [main.py:33] App ended
17-53-2023 11:53:54 INFO     [main.py:19] App started
17-54-2023 11:54:03 INFO     [login.py:29] Employee with e_id:AfqTX, name:Micheal Scott logged in
17-54-2023 11:54:03 INFO     [main_menu.py:45] Employee e_id:AfqTX and designation:manager logged in
17-54-2023 11:54:22 ERROR    [login.py:63] [Customer]: Invalid Username or password with email:acf and password:acf
17-54-2023 11:54:23 INFO     [main_menu.py:122] Customer login failed
17-54-2023 11:54:27 INFO     [main.py:33] App ended
17-54-2023 11:54:48 INFO     [main.py:19] App started
17-54-2023 11:54:55 ERROR    [login.py:63] [Customer]: Invalid Username or password with email:acff and password:acf
17-54-2023 11:54:56 INFO     [main_menu.py:124] Customer login failed
17-54-2023 11:54:56 INFO     [main.py:33] App ended
17-55-2023 11:55:41 INFO     [main.py:19] App started
17-55-2023 11:55:47 ERROR    [login.py:63] [Customer]: Invalid Username or password with email:acf and password:acf
17-55-2023 11:55:52 ERROR    [login.py:63] [Customer]: Invalid Username or password with email:m and password:a
17-55-2023 11:55:53 INFO     [main_menu.py:124] Customer login failed
17-55-2023 11:55:53 INFO     [main.py:33] App ended
17-55-2023 11:55:55 INFO     [main.py:19] App started
17-55-2023 11:55:57 ERROR    [login.py:33] [Employee]: Invalid Username or password with email:a and password:a
17-55-2023 11:55:57 INFO     [main.py:33] App ended
17-57-2023 11:57:08 INFO     [main.py:19] App started
17-57-2023 11:57:13 ERROR    [login.py:33] [Employee]: Invalid Username or password with email:acf and password:ac
17-57-2023 11:57:15 INFO     [main.py:33] App ended
17-57-2023 11:57:17 INFO     [main.py:19] App started
17-57-2023 11:57:21 ERROR    [login.py:33] [Employee]: Invalid Username or password with email:a and password:a
17-57-2023 11:57:26 ERROR    [login.py:33] [Employee]: Invalid Username or password with email:mc and password:mc
17-57-2023 11:57:27 INFO     [main.py:33] App ended
17-57-2023 11:57:37 INFO     [main.py:19] App started
17-57-2023 11:57:41 ERROR    [login.py:67] Customer login: SQLITE_CANTOPEN
17-57-2023 11:57:41 INFO     [main.py:33] App ended
17-57-2023 11:57:44 INFO     [main.py:19] App started
17-57-2023 11:57:52 ERROR    [login.py:45] Employee login: SQLITE_CANTOPEN
17-57-2023 11:57:52 INFO     [main.py:33] App ended
17-57-2023 11:57:59 INFO     [main.py:19] App started
17-58-2023 11:58:43 ERROR    [signup.py:39] Customer login: SQLITE_CANTOPEN
17-58-2023 11:58:43 INFO     [main.py:33] App ended
17-20-2023 14:20:28 INFO     [main.py:19] App started
17-24-2023 14:24:32 INFO     [main.py:19] App started
17-24-2023 14:24:57 INFO     [main.py:19] App started
17-26-2023 14:26:13 INFO     [login.py:29] Employee with e_id:Nmmm8, name:Kelly Kapoor logged in
17-26-2023 14:26:13 INFO     [main_menu.py:47] Employee e_id:Nmmm8 and designation:helpdesk logged in
17-29-2023 14:29:23 INFO     [signup.py:24] New Customer signup with name:Agrima Singh Shukla and email:agrima@muj.manipal.edu
17-29-2023 14:29:41 INFO     [login.py:60] Employee with e_id:XMmqG, name:Agrima Singh Shukla logged in
17-31-2023 14:31:10 INFO     [ticketDAO.py:23] New ticket raised with ticket_id:6r5pn, title:My pc is broken by customer:XMmqG
17-31-2023 14:31:10 INFO     [customer.py:37] Customer:XMmqG is trying to raise a ticket
17-33-2023 14:33:40 INFO     [main.py:33] App ended
17-44-2023 14:44:39 INFO     [main.py:19] App started
17-35-2023 17:35:21 INFO     [main.py:19] App started
17-36-2023 17:36:29 INFO     [signup.py:24] New Customer signup with name:Milind and email:mili@gmail.com
17-36-2023 17:36:40 ERROR    [login.py:63] [Customer]: Invalid Username or password with email:dmm and password:sss
17-36-2023 17:36:42 INFO     [main_menu.py:124] Customer login failed
17-36-2023 17:36:42 INFO     [main.py:33] App ended
17-36-2023 17:36:44 INFO     [main.py:19] App started
17-36-2023 17:36:58 INFO     [login.py:29] Employee with e_id:AfqTX, name:Micheal Scott logged in
17-36-2023 17:36:58 INFO     [main_menu.py:47] Employee e_id:AfqTX and designation:manager logged in
17-37-2023 17:37:30 INFO     [manager_ticket_section.py:47] Manager viewed all tickets in the organization
17-37-2023 17:37:49 INFO     [login.py:29] Employee with e_id:Nmmm8, name:Kelly Kapoor logged in
17-37-2023 17:37:49 INFO     [main_menu.py:47] Employee e_id:Nmmm8 and designation:helpdesk logged in
17-26-2023 18:26:34 INFO     [main.py:19] App started
28-19-2023 10:19:15 INFO     [main.py:19] App started
28-19-2023 10:19:19 INFO     [main.py:33] App ended
28-21-2023 10:21:29 INFO     [main.py:19] App started
28-21-2023 10:21:31 INFO     [main.py:33] App ended
28-23-2023 10:23:48 INFO     [main.py:25] App started
28-26-2023 10:26:39 INFO     [main.py:39] App ended
28-25-2023 12:25:20 INFO     [main.py:25] App started
28-26-2023 12:26:08 INFO     [main.py:25] App started
28-26-2023 12:26:26 ERROR    [login.py:44] Employee login: SQLITE_CANTOPEN
28-26-2023 12:26:26 INFO     [main.py:39] App ended
28-26-2023 12:26:29 INFO     [main.py:25] App started
28-26-2023 12:26:33 INFO     [main.py:39] App ended
28-28-2023 12:28:38 INFO     [main.py:25] App started
28-28-2023 12:28:50 INFO     [login.py:28] Employee with e_id:Nmmm8, name:Kelly Kapoor logged in
28-28-2023 12:28:50 INFO     [main_menu.py:48] Employee e_id:Nmmm8 and designation:helpdesk logged in
28-29-2023 12:29:33 INFO     [main.py:39] App ended
28-36-2023 12:36:51 INFO     [main.py:26] App started
28-36-2023 12:36:52 INFO     [main.py:29] App ended
28-28-2023 13:28:37 INFO     [main.py:25] App started
28-28-2023 13:28:59 INFO     [login.py:30] Employee with e_id:Nmmm8, name:Kelly Kapoor logged in
28-28-2023 13:28:59 INFO     [main_menu.py:48] Employee e_id:Nmmm8 and designation:helpdesk logged in
28-29-2023 13:29:02 INFO     [main.py:28] App ended
28-31-2023 13:31:11 INFO     [main.py:25] App started
29-09-2023 10:09:17 INFO     [main.py:25] App started
29-09-2023 10:09:20 INFO     [main.py:28] App ended
01-41-2023 16:41:42 INFO     [main.py:25] App started
01-41-2023 16:41:59 INFO     [login.py:31] Employee with e_id:Nmmm8, name:Kelly Kapoor logged in
01-41-2023 16:41:59 INFO     [main_menu.py:51] Employee e_id:Nmmm8 and designation:helpdesk logged in
01-42-2023 16:42:23 INFO     [main.py:28] App ended
22-07-2023 15:07:16 INFO     [main.py:24] App started
22-07-2023 15:07:19 INFO     [main.py:27] App ended
22-09-2023 15:09:57 INFO     [main.py:24] App started
25-27-2024 14:27:44 WARNING  [_internal.py:96]  * Debugger is active!
25-27-2024 14:27:44 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-27-2024 14:27:48 INFO     [ticketDAO.py:138] Ticket status changed for ticket_id:6gAXi to closed
25-27-2024 14:27:48 ERROR    [ticket_operation_handler.py:79] There was an error while closing a ticket6gAXi Unread result found
25-27-2024 14:27:48 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:27:48] "[35m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 500 -
25-29-2024 14:29:13 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\ticket\\ticketDAO.py', reloading
25-29-2024 14:29:14 WARNING  [_internal.py:96]  * Debugger is active!
25-29-2024 14:29:14 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-29-2024 14:29:26 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_operation_handler.py', reloading
25-29-2024 14:29:27 WARNING  [_internal.py:96]  * Debugger is active!
25-29-2024 14:29:27 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-29-2024 14:29:30 INFO     [ticketDAO.py:139] Ticket status changed for ticket_id:6gAXi to closed
25-29-2024 14:29:30 ERROR    [ticket_operation_handler.py:77] There was an error while closing a ticket6gAXi Unread result found
25-29-2024 14:29:30 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:29:30] "[35m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 500 -
25-32-2024 14:32:12 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_operation_controller.py', reloading
25-32-2024 14:32:13 WARNING  [_internal.py:96]  * Debugger is active!
25-32-2024 14:32:13 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-32-2024 14:32:58 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\ticket\\ticketDAO.py', reloading
25-32-2024 14:32:59 WARNING  [_internal.py:96]  * Debugger is active!
25-32-2024 14:32:59 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-33-2024 14:33:23 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\ticket\\ticketDAO.py', reloading
25-33-2024 14:33:23 WARNING  [_internal.py:96]  * Debugger is active!
25-33-2024 14:33:24 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-36-2024 14:36:42 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:36:42] "[31m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 401 -
25-36-2024 14:36:51 INFO     [employee_login_handler.py:23] Employee with e_id:SGCxT, role:helpdesk logged in
25-36-2024 14:36:51 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:36:51] "POST /login/employee HTTP/1.1" 200 -
25-36-2024 14:36:57 INFO     [ticketDAO.py:139] Ticket status changed for ticket_id:6gAXi to closed
25-36-2024 14:36:57 ERROR    [ticket_operation_handler.py:77] There was an error while closing a ticket6gAXi Unread result found
25-36-2024 14:36:57 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:36:57] "[35m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 500 -
25-37-2024 14:37:26 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\ticket\\ticketDAO.py', reloading
25-37-2024 14:37:28 WARNING  [_internal.py:96]  * Debugger is active!
25-37-2024 14:37:28 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-37-2024 14:37:39 INFO     [ticketDAO.py:140] Ticket status changed for ticket_id:6gAXi to closed
25-37-2024 14:37:39 ERROR    [ticket_operation_handler.py:77] There was an error while closing a ticket6gAXi Unread result found
25-37-2024 14:37:39 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:37:39] "[35m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 500 -
25-42-2024 14:42:07 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\ticket\\ticketDAO.py', reloading
25-42-2024 14:42:09 WARNING  [_internal.py:96]  * Debugger is active!
25-42-2024 14:42:09 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-42-2024 14:42:20 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\ticket\\ticketDAO.py', reloading
25-42-2024 14:42:21 WARNING  [_internal.py:96]  * Debugger is active!
25-42-2024 14:42:21 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-42-2024 14:42:25 INFO     [ticketDAO.py:141] Ticket status changed for ticket_id:6gAXi to closed
25-42-2024 14:42:25 ERROR    [ticket_operation_handler.py:77] There was an error while closing a ticket6gAXi Truncated incorrect DOUBLE value: 'Hope your issue got solved.'
25-42-2024 14:42:25 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:42:25] "[35m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 500 -
25-42-2024 14:42:58 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\utils\\rbac\\rbac.py', reloading
25-42-2024 14:42:59 WARNING  [_internal.py:96]  * Debugger is active!
25-42-2024 14:42:59 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-43-2024 14:43:05 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
25-43-2024 14:43:05 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
25-43-2024 14:43:05 INFO     [_internal.py:96]  * Restarting with stat
25-43-2024 14:43:06 WARNING  [_internal.py:96]  * Debugger is active!
25-43-2024 14:43:06 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-43-2024 14:43:09 INFO     [ticketDAO.py:141] Ticket status changed for ticket_id:6gAXi to closed
25-43-2024 14:43:09 ERROR    [ticket_operation_handler.py:77] There was an error while closing a ticket6gAXi Truncated incorrect DOUBLE value: 'Hope your issue got solved.'
25-43-2024 14:43:09 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:43:09] "[35m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 500 -
25-43-2024 14:43:55 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\ticket\\ticketDAO.py', reloading
25-43-2024 14:43:55 INFO     [_internal.py:96]  * Restarting with stat
25-43-2024 14:43:56 WARNING  [_internal.py:96]  * Debugger is active!
25-43-2024 14:43:56 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-44-2024 14:44:01 INFO     [ticketDAO.py:143] Ticket status changed for ticket_id:6gAXi to closed
25-44-2024 14:44:01 ERROR    [ticket_operation_handler.py:77] There was an error while closing a ticket6gAXi Truncated incorrect DOUBLE value: 'Hope your issue got solved.'
25-44-2024 14:44:01 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:44:01] "[35m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 500 -
25-54-2024 14:54:11 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
25-54-2024 14:54:11 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
25-54-2024 14:54:11 INFO     [_internal.py:96]  * Restarting with stat
25-54-2024 14:54:12 WARNING  [_internal.py:96]  * Debugger is active!
25-54-2024 14:54:12 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-54-2024 14:54:13 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:54:13] "[31m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 401 -
25-54-2024 14:54:19 INFO     [employee_login_handler.py:23] Employee with e_id:SGCxT, role:helpdesk logged in
25-54-2024 14:54:19 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:54:19] "POST /login/employee HTTP/1.1" 200 -
25-54-2024 14:54:23 INFO     [ticketDAO.py:143] Ticket status changed for ticket_id:6gAXi to closed
25-54-2024 14:54:23 INFO     [ticketDAO.py:126] Message from helpdesk updated for ticket_id:6gAXi to Hope your issue got solved.
25-54-2024 14:54:23 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:54:23] "PUT /tickets/6gAXi/close HTTP/1.1" 200 -
25-55-2024 14:55:25 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_operation_handler.py', reloading
25-55-2024 14:55:25 INFO     [_internal.py:96]  * Restarting with stat
25-55-2024 14:55:26 WARNING  [_internal.py:96]  * Debugger is active!
25-55-2024 14:55:26 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-55-2024 14:55:28 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
25-55-2024 14:55:28 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
25-55-2024 14:55:28 INFO     [_internal.py:96]  * Restarting with stat
25-55-2024 14:55:29 WARNING  [_internal.py:96]  * Debugger is active!
25-55-2024 14:55:29 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
25-55-2024 14:55:31 ERROR    [ticket_operation_handler.py:63] User tried to resolve an already closed or just raised ticket for Ticket Id: 6gAXi
25-55-2024 14:55:31 INFO     [_internal.py:96] 127.0.0.1 - - [25/Jan/2024 14:55:31] "[31m[1mPUT /tickets/6gAXi/close HTTP/1.1[0m" 400 -
27-52-2024 08:52:07 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-52-2024 08:52:07 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-52-2024 08:52:07 INFO     [_internal.py:96]  * Restarting with stat
27-52-2024 08:52:08 WARNING  [_internal.py:96]  * Debugger is active!
27-52-2024 08:52:08 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-52-2024 08:52:47 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
27-52-2024 08:52:47 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 08:52:47] "POST /login/customer HTTP/1.1" 200 -
27-52-2024 08:52:59 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 08:52:59] "[31m[1mGET /tickets/6gAXi HTTP/1.1[0m" 403 -
27-53-2024 08:53:12 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 08:53:12] "GET /tickets HTTP/1.1" 200 -
27-53-2024 08:53:26 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 08:53:26] "GET /tickets/5XJWp HTTP/1.1" 200 -
27-56-2024 08:56:19 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-56-2024 08:56:19 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-56-2024 08:56:19 INFO     [_internal.py:96]  * Restarting with stat
27-56-2024 08:56:20 WARNING  [_internal.py:96]  * Debugger is active!
27-56-2024 08:56:20 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-56-2024 08:56:22 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 08:56:22] "GET /tickets/5XJWp HTTP/1.1" 200 -
27-00-2024 09:00:51 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-00-2024 09:00:51 INFO     [_internal.py:96]  * Restarting with stat
27-00-2024 09:00:52 WARNING  [_internal.py:96]  * Debugger is active!
27-00-2024 09:00:52 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-01-2024 09:01:35 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-01-2024 09:01:35 INFO     [_internal.py:96]  * Restarting with stat
27-01-2024 09:01:36 WARNING  [_internal.py:96]  * Debugger is active!
27-01-2024 09:01:36 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-05-2024 09:05:55 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:05:55] "[33mGET /tickets/5XJWp HTTP/1.1[0m" 404 -
27-06-2024 09:06:05 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:06:05] "GET /tickets HTTP/1.1" 200 -
27-06-2024 09:06:17 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
27-06-2024 09:06:17 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:06:17] "POST /login/customer HTTP/1.1" 200 -
27-06-2024 09:06:22 INFO     [ticketDAO.py:36] New ticket raised with ticket_id:N6qkX, title:Need Help ASAP Urgent Router by customer:5ziph
27-06-2024 09:06:23 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:06:23] "[35m[1mPOST /tickets HTTP/1.1[0m" 201 -
27-06-2024 09:06:38 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:06:38] "GET /tickets/N6qkX HTTP/1.1" 200 -
27-07-2024 09:07:14 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:07:14] "[31m[1mPUT /tickets/N6qkX/resolve HTTP/1.1[0m" 403 -
27-07-2024 09:07:21 INFO     [employee_login_handler.py:23] Employee with e_id:SGCxT, role:helpdesk logged in
27-07-2024 09:07:21 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:07:21] "POST /login/employee HTTP/1.1" 200 -
27-07-2024 09:07:26 INFO     [ticketDAO.py:149] ticket_id: N6qkX assigned to SGCxT
27-07-2024 09:07:26 INFO     [ticketDAO.py:142] Ticket status changed for ticket_id:N6qkX to in_progress
27-07-2024 09:07:26 INFO     [ticketDAO.py:117] Message from helpdesk created for ticket_id:N6qkX, message: hello we will help you.
27-07-2024 09:07:26 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:07:26] "PUT /tickets/N6qkX/resolve HTTP/1.1" 200 -
27-08-2024 09:08:36 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:08:36] "[35m[1mGET /tickets/N6qkX HTTP/1.1[0m" 500 -
27-10-2024 09:10:53 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\ticket\\ticketDAO.py', reloading
27-10-2024 09:10:53 INFO     [_internal.py:96]  * Restarting with stat
27-10-2024 09:10:54 WARNING  [_internal.py:96]  * Debugger is active!
27-10-2024 09:10:54 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-11-2024 09:11:02 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-11-2024 09:11:02 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-11-2024 09:11:02 INFO     [_internal.py:96]  * Restarting with stat
27-11-2024 09:11:03 WARNING  [_internal.py:96]  * Debugger is active!
27-11-2024 09:11:03 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-11-2024 09:11:05 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:11:05] "[35m[1mGET /tickets/N6qkX HTTP/1.1[0m" 500 -
27-11-2024 09:11:38 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-11-2024 09:11:38 INFO     [_internal.py:96]  * Restarting with stat
27-11-2024 09:11:39 WARNING  [_internal.py:96]  * Debugger is active!
27-11-2024 09:11:39 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-11-2024 09:11:42 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-11-2024 09:11:42 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-11-2024 09:11:42 INFO     [_internal.py:96]  * Restarting with stat
27-11-2024 09:11:42 WARNING  [_internal.py:96]  * Debugger is active!
27-11-2024 09:11:42 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-11-2024 09:11:44 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:11:44] "[35m[1mGET /tickets/N6qkX HTTP/1.1[0m" 500 -
27-11-2024 09:11:56 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-11-2024 09:11:56 INFO     [_internal.py:96]  * Restarting with stat
27-11-2024 09:11:56 WARNING  [_internal.py:96]  * Debugger is active!
27-11-2024 09:11:56 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-12-2024 09:12:08 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-12-2024 09:12:08 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-12-2024 09:12:08 INFO     [_internal.py:96]  * Restarting with stat
27-12-2024 09:12:09 WARNING  [_internal.py:96]  * Debugger is active!
27-12-2024 09:12:09 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-12-2024 09:12:13 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:12:13] "GET /tickets/N6qkX HTTP/1.1" 200 -
27-13-2024 09:13:33 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_controller.py', reloading
27-13-2024 09:13:33 INFO     [_internal.py:96]  * Restarting with stat
27-13-2024 09:13:34 WARNING  [_internal.py:96]  * Debugger is active!
27-13-2024 09:13:34 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-13-2024 09:13:37 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-13-2024 09:13:37 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-13-2024 09:13:37 INFO     [_internal.py:96]  * Restarting with stat
27-13-2024 09:13:37 WARNING  [_internal.py:96]  * Debugger is active!
27-13-2024 09:13:37 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-13-2024 09:13:39 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:13:39] "GET /tickets/N6qkX HTTP/1.1" 200 -
27-13-2024 09:13:50 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
27-13-2024 09:13:50 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:13:50] "POST /login/customer HTTP/1.1" 200 -
27-13-2024 09:13:53 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:13:53] "GET /tickets/N6qkX HTTP/1.1" 200 -
27-19-2024 09:19:54 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_controller.py', reloading
27-19-2024 09:19:54 INFO     [_internal.py:96]  * Restarting with stat
27-19-2024 09:19:55 WARNING  [_internal.py:96]  * Debugger is active!
27-19-2024 09:19:55 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-20-2024 09:20:15 INFO     [ticketDAO.py:36] New ticket raised with ticket_id:SY6RR, title:Need Help ASAP Urgent PC by customer:5ziph
27-20-2024 09:20:15 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:20:15] "[35m[1mPOST /tickets HTTP/1.1[0m" 201 -
27-20-2024 09:20:20 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:20:20] "[35m[1mGET /tickets/N6qkX HTTP/1.1[0m" 500 -
27-20-2024 09:20:42 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_controller.py', reloading
27-20-2024 09:20:42 INFO     [_internal.py:96]  * Restarting with stat
27-20-2024 09:20:43 WARNING  [_internal.py:96]  * Debugger is active!
27-20-2024 09:20:43 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-20-2024 09:20:46 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-20-2024 09:20:46 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-20-2024 09:20:46 INFO     [_internal.py:96]  * Restarting with stat
27-20-2024 09:20:47 WARNING  [_internal.py:96]  * Debugger is active!
27-20-2024 09:20:47 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-20-2024 09:20:51 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:20:51] "GET /tickets/N6qkX HTTP/1.1" 200 -
27-21-2024 09:21:09 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:21:09] "GET /tickets/SY6RR HTTP/1.1" 200 -
27-21-2024 09:21:22 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:21:22] "GET /tickets/N6qkX HTTP/1.1" 200 -
27-22-2024 09:22:12 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_controller.py', reloading
27-22-2024 09:22:13 INFO     [_internal.py:96]  * Restarting with stat
27-22-2024 09:22:13 WARNING  [_internal.py:96]  * Debugger is active!
27-22-2024 09:22:13 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-27-2024 09:27:12 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_controller.py', reloading
27-27-2024 09:27:12 INFO     [_internal.py:96]  * Restarting with stat
27-27-2024 09:27:13 WARNING  [_internal.py:96]  * Debugger is active!
27-27-2024 09:27:13 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-27-2024 09:27:30 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-27-2024 09:27:30 INFO     [_internal.py:96]  * Restarting with stat
27-27-2024 09:27:31 WARNING  [_internal.py:96]  * Debugger is active!
27-27-2024 09:27:31 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-30-2024 09:30:58 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-30-2024 09:30:58 INFO     [_internal.py:96]  * Restarting with stat
27-30-2024 09:30:59 WARNING  [_internal.py:96]  * Debugger is active!
27-30-2024 09:30:59 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-31-2024 09:31:06 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-31-2024 09:31:06 INFO     [_internal.py:96]  * Restarting with stat
27-31-2024 09:31:07 WARNING  [_internal.py:96]  * Debugger is active!
27-31-2024 09:31:07 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-31-2024 09:31:35 INFO     [employee_login_handler.py:23] Employee with e_id:SGCxT, role:helpdesk logged in
27-31-2024 09:31:35 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:31:35] "POST /login/employee HTTP/1.1" 200 -
27-31-2024 09:31:42 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:31:42] "GET /tickets HTTP/1.1" 200 -
27-31-2024 09:31:56 INFO     [ticketDAO.py:139] Ticket status changed for ticket_id:N6qkX to closed
27-31-2024 09:31:56 INFO     [ticketDAO.py:125] Message from helpdesk updated for ticket_id:N6qkX to Hope your issue got solved.
27-31-2024 09:31:56 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:31:56] "PUT /tickets/N6qkX/close HTTP/1.1" 200 -
27-32-2024 09:32:05 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
27-32-2024 09:32:05 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:32:05] "POST /login/customer HTTP/1.1" 200 -
27-32-2024 09:32:15 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:32:15] "[31m[1mGET /tickets/N6qkX HTTP/1.1[0m" 403 -
27-32-2024 09:32:35 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:32:35] "[31m[1mGET /tickets/N6qkX HTTP/1.1[0m" 403 -
27-33-2024 09:33:02 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
27-33-2024 09:33:02 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:33:02] "POST /login/customer HTTP/1.1" 200 -
27-33-2024 09:33:05 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:33:05] "[31m[1mGET /tickets/N6qkX HTTP/1.1[0m" 403 -
27-33-2024 09:33:51 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-33-2024 09:33:51 INFO     [_internal.py:96]  * Restarting with stat
27-33-2024 09:33:52 WARNING  [_internal.py:96]  * Debugger is active!
27-33-2024 09:33:52 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-33-2024 09:33:56 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-33-2024 09:33:56 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-33-2024 09:33:56 INFO     [_internal.py:96]  * Restarting with stat
27-33-2024 09:33:57 WARNING  [_internal.py:96]  * Debugger is active!
27-33-2024 09:33:57 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-33-2024 09:33:58 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:33:58] "[31m[1mGET /tickets/N6qkX HTTP/1.1[0m" 403 -
27-34-2024 09:34:59 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-34-2024 09:34:59 INFO     [_internal.py:96]  * Restarting with stat
27-35-2024 09:35:00 WARNING  [_internal.py:96]  * Debugger is active!
27-35-2024 09:35:00 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-35-2024 09:35:01 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-35-2024 09:35:01 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-35-2024 09:35:01 INFO     [_internal.py:96]  * Restarting with stat
27-35-2024 09:35:02 WARNING  [_internal.py:96]  * Debugger is active!
27-35-2024 09:35:02 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-35-2024 09:35:04 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:35:04] "[31m[1mGET /tickets/N6qkX HTTP/1.1[0m" 403 -
27-35-2024 09:35:15 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-35-2024 09:35:15 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-35-2024 09:35:15 INFO     [_internal.py:96]  * Restarting with stat
27-35-2024 09:35:16 WARNING  [_internal.py:96]  * Debugger is active!
27-35-2024 09:35:16 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-35-2024 09:35:18 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:35:18] "[31m[1mGET /tickets/N6qkX HTTP/1.1[0m" 403 -
27-35-2024 09:35:44 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_controller.py', reloading
27-35-2024 09:35:44 INFO     [_internal.py:96]  * Restarting with stat
27-35-2024 09:35:45 WARNING  [_internal.py:96]  * Debugger is active!
27-35-2024 09:35:45 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-35-2024 09:35:56 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-35-2024 09:35:56 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-35-2024 09:35:56 INFO     [_internal.py:96]  * Restarting with stat
27-35-2024 09:35:57 WARNING  [_internal.py:96]  * Debugger is active!
27-35-2024 09:35:57 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-35-2024 09:35:59 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:35:59] "[31m[1mGET /tickets/N6qkX HTTP/1.1[0m" 403 -
27-36-2024 09:36:36 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-36-2024 09:36:36 INFO     [_internal.py:96]  * Restarting with stat
27-36-2024 09:36:37 WARNING  [_internal.py:96]  * Debugger is active!
27-36-2024 09:36:37 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-36-2024 09:36:40 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-36-2024 09:36:40 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-36-2024 09:36:40 INFO     [_internal.py:96]  * Restarting with stat
27-36-2024 09:36:41 WARNING  [_internal.py:96]  * Debugger is active!
27-36-2024 09:36:41 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-36-2024 09:36:49 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-36-2024 09:36:49 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-36-2024 09:36:52 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 09:36:52] "GET /tickets/N6qkX HTTP/1.1" 200 -
27-01-2024 11:03:33 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-01-2024 11:03:33 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-01-2024 11:03:40 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:03:40] "[31m[1mGET /tickets/N6qkX HTTP/1.1[0m" 401 -
27-01-2024 11:03:47 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
27-01-2024 11:03:47 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:03:47] "POST /login/customer HTTP/1.1" 200 -
27-01-2024 11:03:50 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:03:50] "[35m[1mGET /tickets HTTP/1.1[0m" 500 -
27-01-2024 11:03:50 ERROR    [_internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\blueprint.py", line 297, in wrapper
    return func(*f_args, **f_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\utils\rbac\rbac.py", line 23, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\resources\ticket\ticket.py", line 22, in get
    all_tickets = TicketController.get_all_tickets_concise_view(identity, role)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\controllers\ticket\ticket_controller.py", line 65, in get_all_tickets_concise_view
    tickets = TicketHandler.get_tickets_by_identity_and_role(role, identity)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TicketHandler.get_tickets_by_identity_and_role() missing 1 required positional argument: 'identity'
27-01-2024 11:03:55 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:03:55] "[35m[1mGET /tickets HTTP/1.1[0m" 500 -
27-01-2024 11:03:55 ERROR    [_internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\blueprint.py", line 297, in wrapper
    return func(*f_args, **f_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\utils\rbac\rbac.py", line 23, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\resources\ticket\ticket.py", line 22, in get
    all_tickets = TicketController.get_all_tickets_concise_view(identity, role)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\controllers\ticket\ticket_controller.py", line 65, in get_all_tickets_concise_view
    tickets = TicketHandler.get_tickets_by_identity_and_role(role, identity)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TicketHandler.get_tickets_by_identity_and_role() missing 1 required positional argument: 'identity'
27-01-2024 11:04:06 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-01-2024 11:04:06 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-01-2024 11:04:10 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:04:10] "[35m[1mGET /tickets HTTP/1.1[0m" 500 -
27-01-2024 11:04:10 ERROR    [_internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\blueprint.py", line 297, in wrapper
    return func(*f_args, **f_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\utils\rbac\rbac.py", line 23, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\resources\ticket\ticket.py", line 22, in get
    all_tickets = TicketController.get_all_tickets_concise_view(identity, role)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\controllers\ticket\ticket_controller.py", line 65, in get_all_tickets_concise_view
    tickets = TicketHandler.get_tickets_by_identity_and_role(role, identity)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TicketHandler.get_tickets_by_identity_and_role() missing 1 required positional argument: 'identity'
27-01-2024 11:04:24 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
27-01-2024 11:04:24 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:04:24] "POST /login/customer HTTP/1.1" 200 -
27-01-2024 11:04:37 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-01-2024 11:04:37 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-01-2024 11:04:37 INFO     [_internal.py:96]  * Restarting with stat
27-01-2024 11:04:38 WARNING  [_internal.py:96]  * Debugger is active!
27-01-2024 11:04:38 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-01-2024 11:04:54 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\customer\\feedbackdao.py', reloading
27-01-2024 11:04:54 INFO     [_internal.py:96]  * Restarting with stat
27-01-2024 11:04:55 WARNING  [_internal.py:96]  * Debugger is active!
27-01-2024 11:04:55 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-01-2024 11:04:58 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
27-01-2024 11:04:58 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:04:58] "POST /login/customer HTTP/1.1" 200 -
27-01-2024 11:05:00 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
27-01-2024 11:05:00 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:05:00] "POST /login/customer HTTP/1.1" 200 -
27-01-2024 11:05:12 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:05:12] "[35m[1mGET /tickets HTTP/1.1[0m" 500 -
27-01-2024 11:05:39 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-01-2024 11:05:39 INFO     [_internal.py:96]  * Restarting with stat
27-01-2024 11:05:40 WARNING  [_internal.py:96]  * Debugger is active!
27-01-2024 11:05:40 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-01-2024 11:05:50 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
27-01-2024 11:05:50 INFO     [_internal.py:96]  * Restarting with stat
27-01-2024 11:05:51 WARNING  [_internal.py:96]  * Debugger is active!
27-01-2024 11:05:51 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-01-2024 11:05:53 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-01-2024 11:05:53 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-01-2024 11:05:53 INFO     [_internal.py:96]  * Restarting with stat
27-01-2024 11:05:54 WARNING  [_internal.py:96]  * Debugger is active!
27-01-2024 11:05:54 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-01-2024 11:05:55 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:05:55] "GET /tickets HTTP/1.1" 200 -
27-01-2024 11:07:13 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:07:13] "[31m[1mPOST /tickets/N6qkX/feedback HTTP/1.1[0m" 401 -
27-01-2024 11:07:27 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:07:27] "[35m[1mPOST /tickets/N6qkX/feedback HTTP/1.1[0m" 500 -
27-01-2024 11:08:05 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\feedback\\feedback.py', reloading
27-01-2024 11:08:05 INFO     [_internal.py:96]  * Restarting with stat
27-01-2024 11:08:08 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
27-01-2024 11:08:08 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
27-01-2024 11:08:08 INFO     [_internal.py:96]  * Restarting with stat
27-01-2024 11:08:09 WARNING  [_internal.py:96]  * Debugger is active!
27-01-2024 11:08:09 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
27-01-2024 11:08:10 ERROR    [feedback_handler.py:33] Error while adding feedback for ticket N6qkX. Error 1062 (23000): Duplicate entry 'N6qkX' for key 'feedback.t_id'
27-01-2024 11:08:10 INFO     [_internal.py:96] 127.0.0.1 - - [27/Jan/2024 11:08:10] "[35m[1mPOST /tickets/N6qkX/feedback HTTP/1.1[0m" 500 -
29-01-2024 11:03:10 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 11:03:10 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 11:03:10 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:03:11 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:03:11 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:04:04 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:04:04] "GET /tickets/N6qkX/feedback HTTP/1.1" 200 -
29-01-2024 11:04:39 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\feedback\\feedback.py', reloading
29-01-2024 11:04:39 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:04:40 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:04:40 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:04:46 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 11:04:46 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 11:04:46 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:04:46 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:04:46 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:04:48 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:04:48] "[31m[1mGET /tickets/N6qkX/feedback HTTP/1.1[0m" 401 -
29-01-2024 11:05:16 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:05:16] "[31m[1mGET /tickets/N6qkX/feedback HTTP/1.1[0m" 401 -
29-01-2024 11:05:23 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
29-01-2024 11:05:23 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:05:23] "POST /login/customer HTTP/1.1" 200 -
29-01-2024 11:05:28 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:05:28] "GET /tickets/N6qkX/feedback HTTP/1.1" 200 -
29-01-2024 11:15:17 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\feedback\\feedback_handler.py', reloading
29-01-2024 11:15:17 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:15:18 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:15:18 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:15:43 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 11:15:43 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 11:15:43 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:15:43 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:15:43 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:15:48 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:15:48] "GET /tickets/N6qkX/feedback HTTP/1.1" 200 -
29-01-2024 11:16:13 INFO     [employee_login_handler.py:23] Employee with e_id:LLYWi, role:manager logged in
29-01-2024 11:16:13 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:16:13] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 11:16:17 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:16:17] "GET /tickets HTTP/1.1" 200 -
29-01-2024 11:16:31 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
29-01-2024 11:16:31 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:16:31] "POST /login/customer HTTP/1.1" 200 -
29-01-2024 11:16:47 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:16:47] "[33mGET /tickets/SY6RR/feedback HTTP/1.1[0m" 404 -
29-01-2024 11:17:13 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': 'QhZ3n', 'email': 'johndoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
29-01-2024 11:17:13 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:17:13] "POST /login/customer HTTP/1.1" 200 -
29-01-2024 11:17:53 INFO     [ticketDAO.py:34] New ticket raised with ticket_id:GjcfW, title:Need Help ASAP PC by customer:QhZ3n
29-01-2024 11:17:53 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:17:53] "[35m[1mPOST /tickets HTTP/1.1[0m" 201 -
29-01-2024 11:18:11 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
29-01-2024 11:18:11 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:18:11] "POST /login/customer HTTP/1.1" 200 -
29-01-2024 11:18:20 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:18:20] "[31m[1mGET /tickets/GjcfW/feedback HTTP/1.1[0m" 401 -
29-01-2024 11:18:34 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:18:34] "[31m[1mPOST /tickets/GjcfW/feedback HTTP/1.1[0m" 403 -
29-01-2024 11:20:52 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 11:20:52 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:20:53 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:20:53 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:21:24 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 11:21:24 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:21:25 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:21:25 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:21:42 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 11:21:42 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:21:42 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:21:42 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:24:11 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 11:24:11 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:24:12 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:24:12 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:25:06 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\message\\messagedao.py', reloading
29-01-2024 11:25:06 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:25:07 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:25:07 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:31:58 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\config\\queries_config_loader.py', reloading
29-01-2024 11:31:58 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:31:59 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:31:59 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:33:36 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\message\\messagedao.py', reloading
29-01-2024 11:33:36 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:33:37 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:33:37 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:35:00 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\message\\messagedao.py', reloading
29-01-2024 11:35:00 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:35:01 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:35:01 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:46:59 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\message\\messagedao.py', reloading
29-01-2024 11:46:59 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:47:00 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:47:00 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:47:04 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\message\\message_handler.py', reloading
29-01-2024 11:47:04 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:47:05 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:47:05 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:48:37 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 11:48:37 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:48:38 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:48:38 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:48:42 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\message\\message_handler.py', reloading
29-01-2024 11:48:43 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:48:43 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:48:43 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:50:28 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 11:50:28 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:50:28 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:50:28 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:50:40 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 11:50:41 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:50:41 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:50:41 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:54:55 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\schemas\\ticket.py', reloading
29-01-2024 11:54:55 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:54:56 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:54:56 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:54:59 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\schemas\\ticket.py', reloading
29-01-2024 11:54:59 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:55:00 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:55:00 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:56:30 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\message\\message.py', reloading
29-01-2024 11:56:30 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:56:31 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:56:31 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:57:52 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 11:57:52 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:57:52 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:57:52 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:57:59 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 11:57:59 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 11:57:59 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 11:58:00 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 11:58:00 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 11:59:30 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:59:30] "[31m[1mPUT /tickets/GjcfW/message HTTP/1.1[0m" 422 -
29-01-2024 11:59:39 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:59:39] "[31m[1mPUT /tickets/GjcfW/message HTTP/1.1[0m" 401 -
29-01-2024 11:59:51 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 11:59:51] "[31m[1mPUT /tickets/GjcfW/message HTTP/1.1[0m" 401 -
29-01-2024 12:00:01 INFO     [employee_login_handler.py:23] Employee with e_id:LLYWi, role:manager logged in
29-01-2024 12:00:01 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 12:00:01] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 12:00:04 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 12:00:04] "[35m[1mPUT /tickets/GjcfW/message HTTP/1.1[0m" 500 -
29-01-2024 12:00:46 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\message\\message.py', reloading
29-01-2024 12:00:46 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:00:47 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 12:00:47 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 12:01:15 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 12:01:15 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:01:16 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 12:01:16 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 12:01:19 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 12:01:19 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 12:01:19 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:01:20 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 12:01:20 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 12:01:26 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 12:01:26] "PUT /tickets/GjcfW/message HTTP/1.1" 200 -
29-01-2024 12:04:35 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\message\\message_handler.py', reloading
29-01-2024 12:04:35 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:04:41 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:08:40 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:08:45 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:08:45 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 12:08:45 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 12:08:56 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 12:08:56] "PUT /tickets/GjcfW/message HTTP/1.1" 200 -
29-01-2024 12:09:43 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\message\\message.py', reloading
29-01-2024 12:09:43 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:09:44 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 12:09:44 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 12:10:16 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\message\\message.py', reloading
29-01-2024 12:10:16 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:10:16 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 12:10:16 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 12:10:42 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 12:10:42] "[31m[1mGET /tickets/GjcfW/message HTTP/1.1[0m" 401 -
29-01-2024 12:10:53 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 12:10:53] "[31m[1mGET /tickets/GjcfW/message HTTP/1.1[0m" 403 -
29-01-2024 12:11:05 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\message\\message.py', reloading
29-01-2024 12:11:06 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 12:11:06 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 12:11:06 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 12:11:07 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 12:11:07] "GET /tickets/GjcfW/message HTTP/1.1" 200 -
29-01-2024 12:11:27 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 12:11:27] "PUT /tickets/GjcfW/message HTTP/1.1" 200 -
29-01-2024 12:11:30 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 12:11:30] "GET /tickets/GjcfW/message HTTP/1.1" 200 -
29-01-2024 13:07:18 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 13:07:19 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:07:19 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:07:19 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:08:28 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 13:14:18 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 13:14:18 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 13:14:18 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:14:19 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:14:19 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:14:24 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:14:24] "[31m[1mGET /tickets/GjcfW/message HTTP/1.1[0m" 401 -
29-01-2024 13:14:46 INFO     [employee_login_handler.py:23] Employee with e_id:SGCxT, role:helpdesk logged in
29-01-2024 13:14:46 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:14:46] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 13:14:51 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:14:51] "[35m[1mGET /tickets/GjcfW/message HTTP/1.1[0m" 500 -
29-01-2024 13:15:13 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 13:15:13 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:15:14 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:15:14 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:15:19 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 13:15:19 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 13:15:19 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:15:20 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:15:20 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:15:22 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:15:22] "[35m[1mGET /tickets/GjcfW/message HTTP/1.1[0m" 500 -
29-01-2024 13:15:38 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 13:15:38 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:15:39 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:15:39 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:15:45 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:15:45] "GET /tickets HTTP/1.1" 200 -
29-01-2024 13:15:59 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:15:59] "[35m[1mGET /tickets/N6qkX/message HTTP/1.1[0m" 500 -
29-01-2024 13:16:38 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\message\\message_handler.py', reloading
29-01-2024 13:16:38 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:16:39 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:16:39 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:16:42 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 13:16:42 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 13:16:42 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:16:43 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:16:43 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:16:45 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:16:45] "[35m[1mGET /tickets/N6qkX/message HTTP/1.1[0m" 500 -
29-01-2024 13:17:21 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 13:17:21 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:17:22 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:17:22 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:19:20 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\message\\message_handler.py', reloading
29-01-2024 13:19:20 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:19:20 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:19:20 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:22:21 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\message\\message_handler.py', reloading
29-01-2024 13:22:21 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:22:24 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 13:22:24 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 13:22:24 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:22:25 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:22:25 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:22:26 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:22:26] "[33mGET /tickets/N6qkX/message HTTP/1.1[0m" 404 -
29-01-2024 13:22:35 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:22:35] "[31m[1mGET /tickets/GjcfW/message HTTP/1.1[0m" 403 -
29-01-2024 13:22:47 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:22:47] "GET /tickets/GjcfW HTTP/1.1" 200 -
29-01-2024 13:23:13 INFO     [employee_login_handler.py:23] Employee with e_id:SGCxT, role:helpdesk logged in
29-01-2024 13:23:13 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:23:13] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 13:23:15 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:23:15] "GET /tickets/GjcfW HTTP/1.1" 200 -
29-01-2024 13:23:40 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:23:40] "GET /tickets/N6qkX HTTP/1.1" 200 -
29-01-2024 13:23:53 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:23:53] "[33mGET /tickets/N6qkX/message HTTP/1.1[0m" 404 -
29-01-2024 13:24:19 INFO     [employee_login_handler.py:23] Employee with e_id:LLYWi, role:manager logged in
29-01-2024 13:24:19 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:24:19] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 13:24:29 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:24:29] "PUT /tickets/N6qkX/message HTTP/1.1" 200 -
29-01-2024 13:24:47 INFO     [employee_login_handler.py:23] Employee with e_id:SGCxT, role:helpdesk logged in
29-01-2024 13:24:47 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:24:47] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 13:25:02 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:25:02] "GET /tickets/N6qkX/message HTTP/1.1" 200 -
29-01-2024 13:29:38 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\message\\message_handler.py', reloading
29-01-2024 13:29:38 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:29:39 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:29:39 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:29:56 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 13:29:56 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 13:29:56 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:29:56 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:29:56 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:38:40 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 13:38:40 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 13:38:40 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:38:40 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:38:40 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:38:43 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
29-01-2024 13:38:43 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:38:43] "POST /login/customer HTTP/1.1" 200 -
29-01-2024 13:38:52 INFO     [ticketDAO.py:34] New ticket raised with ticket_id:Fqw7n, title:Need Help ASAP PC by customer:5ziph
29-01-2024 13:38:52 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:38:52] "[35m[1mPOST /tickets HTTP/1.1[0m" 201 -
29-01-2024 13:39:05 INFO     [employee_login_handler.py:23] Employee with e_id:SGCxT, role:helpdesk logged in
29-01-2024 13:39:05 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:39:05] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 13:39:30 INFO     [employee_login_handler.py:23] Employee with e_id:SGCxT, role:helpdesk logged in
29-01-2024 13:39:30 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:39:30] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 13:40:33 INFO     [ticketDAO.py:142] ticket_id: Fqw7n assigned to SGCxT
29-01-2024 13:40:33 INFO     [ticketDAO.py:135] Ticket status changed for ticket_id:Fqw7n to in_progress
29-01-2024 13:40:33 INFO     [ticketDAO.py:113] Message from helpdesk created for ticket_id:Fqw7n, message: Our IT team is on its way to solve the issue.
29-01-2024 13:40:33 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:40:33] "PUT /tickets/Fqw7n/resolve HTTP/1.1" 200 -
29-01-2024 13:40:44 INFO     [ticketDAO.py:135] Ticket status changed for ticket_id:Fqw7n to closed
29-01-2024 13:40:44 INFO     [ticketDAO.py:121] Message from helpdesk updated for ticket_id:Fqw7n to Hope your issue got solved.
29-01-2024 13:40:44 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:40:44] "PUT /tickets/Fqw7n/close HTTP/1.1" 200 -
29-01-2024 13:40:58 INFO     [employee_login_handler.py:23] Employee with e_id:LLYWi, role:manager logged in
29-01-2024 13:40:58 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:40:58] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 13:41:14 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:41:14] "[33mGET /tickets/Fqw7n/message HTTP/1.1[0m" 404 -
29-01-2024 13:41:23 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:41:23] "[35m[1mPUT /tickets/Fqw7n/message HTTP/1.1[0m" 500 -
29-01-2024 13:42:01 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 13:42:01 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:42:02 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:42:02 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:42:08 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:42:08] "[33mPUT /tickets/Fqw7n/message HTTP/1.1[0m" 404 -
29-01-2024 13:42:18 INFO     [customer_login_handler.py:22] Employee with c_id:{'c_id': '5ziph', 'email': 'janedoe@gmail.com', 'password': 'a8cb0ee32ac29ec17c40252725d951fd285c19e4e36845db6a1d5ac9d183682a'} logged in
29-01-2024 13:42:18 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:42:18] "POST /login/customer HTTP/1.1" 200 -
29-01-2024 13:42:23 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:42:23] "GET /tickets HTTP/1.1" 200 -
29-01-2024 13:42:32 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:42:32] "GET /tickets/Fqw7n HTTP/1.1" 200 -
29-01-2024 13:43:05 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:43:05] "[35m[1mPOST /tickets/Fqw7n/feedback HTTP/1.1[0m" 201 -
29-01-2024 13:43:10 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:43:10] "[35m[1mGET /tickets/GjcfW/feedback HTTP/1.1[0m" 500 -
29-01-2024 13:43:18 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\message\\message_controller.py', reloading
29-01-2024 13:43:18 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:43:19 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:43:19 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:43:29 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:43:29] "GET /tickets/Fqw7n/feedback HTTP/1.1" 200 -
29-01-2024 13:43:48 INFO     [employee_login_handler.py:23] Employee with e_id:LLYWi, role:manager logged in
29-01-2024 13:43:48 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:43:48] "POST /login/employee HTTP/1.1" 200 -
29-01-2024 13:43:54 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:43:54] "[31m[1mGET /tickets/Fqw7n/feedback HTTP/1.1[0m" 401 -
29-01-2024 13:44:43 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\feedback\\feedback_controller.py', reloading
29-01-2024 13:44:43 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:44:44 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:44:44 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:44:48 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 13:44:48 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 13:44:48 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:44:49 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:44:49 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:44:53 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:44:53] "[31m[1mGET /tickets/Fqw7n/feedback HTTP/1.1[0m" 401 -
29-01-2024 13:46:02 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\feedback\\feedback.py', reloading
29-01-2024 13:46:02 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:46:03 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:46:03 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:46:06 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
29-01-2024 13:46:06 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
29-01-2024 13:46:06 INFO     [_internal.py:96]  * Restarting with stat
29-01-2024 13:46:07 WARNING  [_internal.py:96]  * Debugger is active!
29-01-2024 13:46:07 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
29-01-2024 13:46:09 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:46:09] "GET /tickets/Fqw7n/feedback HTTP/1.1" 200 -
29-01-2024 13:46:17 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:46:17] "PUT /tickets/Fqw7n/message HTTP/1.1" 200 -
29-01-2024 13:46:23 INFO     [_internal.py:96] 127.0.0.1 - - [29/Jan/2024 13:46:23] "GET /tickets/Fqw7n/message HTTP/1.1" 200 -
31-01-2024 11:46:57 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 11:46:57 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 11:47:30 INFO     [customer_signup_handler.py:35] New Customer signup with name:Mr. abc and email:abc@gmail.com
31-01-2024 11:47:30 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:47:30] "[35m[1mPOST /signup HTTP/1.1[0m" 201 -
31-01-2024 11:47:45 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 11:47:45 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:47:45] "[35m[1mPOST /login/customer HTTP/1.1[0m" 500 -
31-01-2024 11:47:45 ERROR    [_internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\webargs\core.py", line 649, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\arguments.py", line 82, in wrapper
    return func(*f_args, **f_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\resources\users\user.py", line 19, in post
    token = CustomerLoginController.login(cust_auth_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\controllers\authentication\customer\customer_login_controller.py", line 14, in login
    token = CustomerLoginHandler.generate_token(cust_id=customer['c_id'])
                                                        ^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
31-01-2024 11:47:51 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 11:47:51 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:47:51] "[35m[1mPOST /login/customer HTTP/1.1[0m" 500 -
31-01-2024 11:47:51 ERROR    [_internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\webargs\core.py", line 649, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\arguments.py", line 82, in wrapper
    return func(*f_args, **f_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\resources\users\user.py", line 19, in post
    token = CustomerLoginController.login(cust_auth_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\controllers\authentication\customer\customer_login_controller.py", line 14, in login
    token = CustomerLoginHandler.generate_token(cust_id=customer['c_id'])
                                                        ^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
31-01-2024 11:48:24 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 11:48:24 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:48:24] "[35m[1mPOST /login/customer HTTP/1.1[0m" 500 -
31-01-2024 11:48:24 ERROR    [_internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\webargs\core.py", line 649, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\arguments.py", line 82, in wrapper
    return func(*f_args, **f_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\resources\users\user.py", line 19, in post
    token = CustomerLoginController.login(cust_auth_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\controllers\authentication\customer\customer_login_controller.py", line 14, in login
    token = CustomerLoginHandler.generate_token(cust_id=customer['c_id'])
                                                        ^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
31-01-2024 11:48:25 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 11:48:25 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:48:25] "[35m[1mPOST /login/customer HTTP/1.1[0m" 500 -
31-01-2024 11:48:25 ERROR    [_internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\webargs\core.py", line 649, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\arguments.py", line 82, in wrapper
    return func(*f_args, **f_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\resources\users\user.py", line 19, in post
    token = CustomerLoginController.login(cust_auth_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\controllers\authentication\customer\customer_login_controller.py", line 14, in login
    token = CustomerLoginHandler.generate_token(cust_id=customer['c_id'])
                                                        ^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
31-01-2024 11:48:55 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 11:48:55 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:48:55] "[35m[1mPOST /login/customer HTTP/1.1[0m" 500 -
31-01-2024 11:48:55 ERROR    [_internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\webargs\core.py", line 649, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\arguments.py", line 82, in wrapper
    return func(*f_args, **f_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\resources\users\user.py", line 19, in post
    token = CustomerLoginController.login(cust_auth_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\controllers\authentication\customer\customer_login_controller.py", line 14, in login
    token = CustomerLoginHandler.generate_token(cust_id=customer['c_id'])
                                                        ^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
31-01-2024 11:49:40 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 11:49:40 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 11:49:45 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 11:49:45 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:49:45] "[35m[1mPOST /login/customer HTTP/1.1[0m" 500 -
31-01-2024 11:49:45 ERROR    [_internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask\views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\webargs\core.py", line 649, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\arguments.py", line 82, in wrapper
    return func(*f_args, **f_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\.virtualenvs\CSM-nMsP_ctb\Lib\site-packages\flask_smorest\response.py", line 89, in wrapper
    func(*args, **kwargs)
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\resources\users\user.py", line 19, in post
    token = CustomerLoginController.login(cust_auth_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbhatnagar\PycharmProjects\CSM\src\controllers\authentication\customer\customer_login_controller.py", line 14, in login
    token = CustomerLoginHandler.generate_token(cust_id=customer['c_id'])
                                                        ^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
31-01-2024 11:50:00 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 11:50:00 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 11:50:00 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:50:00 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:50:01 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:50:03 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 11:50:03 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:50:03] "[35m[1mPOST /login/customer HTTP/1.1[0m" 500 -
31-01-2024 11:50:48 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\authentication\\customer\\customer_login_controller.py', reloading
31-01-2024 11:50:48 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:50:49 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:50:49 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:50:52 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 11:50:52 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 11:50:52 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:50:53 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:50:53 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:50:55 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 11:50:55 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:50:55] "POST /login/customer HTTP/1.1" 200 -
31-01-2024 11:51:06 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:51:06] "[35m[1mGET /tickets HTTP/1.1[0m" 500 -
31-01-2024 11:51:46 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 11:51:46 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 11:51:46 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:51:47 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:51:47 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:51:49 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:51:49] "GET /tickets HTTP/1.1" 200 -
31-01-2024 11:52:40 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\ticket\\ticket.py', reloading
31-01-2024 11:52:40 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:52:46 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:52:47 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:52:47 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:52:51 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:52:51] "GET /tickets HTTP/1.1" 200 -
31-01-2024 11:53:40 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\ticket\\ticket.py', reloading
31-01-2024 11:53:40 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:53:41 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:53:41 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:53:48 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
31-01-2024 11:53:49 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:53:49 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:53:49 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:53:52 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:53:52] "GET /tickets HTTP/1.1" 200 -
31-01-2024 11:54:45 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
31-01-2024 11:54:45 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:54:46 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:54:46 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:54:48 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:54:48] "GET /tickets HTTP/1.1" 200 -
31-01-2024 11:55:15 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\utils\\load_configurations.py', reloading
31-01-2024 11:55:15 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:55:16 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:55:16 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:55:20 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 11:55:20 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 11:55:20 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:55:21 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:55:21 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:55:23 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:55:23] "GET /tickets HTTP/1.1" 200 -
31-01-2024 11:55:33 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\utils\\load_configurations.py', reloading
31-01-2024 11:55:33 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:55:34 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:55:34 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:55:51 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
31-01-2024 11:55:51 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:55:52 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:55:52 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:55:57 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:55:57] "[35m[1mPOST /tickets HTTP/1.1[0m" 500 -
31-01-2024 11:56:51 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\new_ticket_handler.py', reloading
31-01-2024 11:56:51 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:56:53 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 11:56:53 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 11:56:53 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:56:54 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:56:54 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 11:56:55 INFO     [ticketDAO.py:34] New ticket raised with ticket_id:FfKC7, title:Need Help ASAP PC by customer:RPfe5
31-01-2024 11:56:55 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:56:55] "[35m[1mPOST /tickets HTTP/1.1[0m" 201 -
31-01-2024 11:57:19 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:57:19] "GET /tickets?ticket_status=closed HTTP/1.1" 200 -
31-01-2024 11:57:27 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:57:27] "GET /tickets?ticket_status=raised HTTP/1.1" 200 -
31-01-2024 11:57:35 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:57:35] "GET /tickets?ticket_status=in_progress HTTP/1.1" 200 -
31-01-2024 11:57:42 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:57:42] "GET /tickets HTTP/1.1" 200 -
31-01-2024 11:57:57 INFO     [employee_login_handler.py:32] Employee with e_id:LLYWi, role:manager logged in
31-01-2024 11:57:57 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:57:57] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 11:58:01 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:58:01] "GET /tickets HTTP/1.1" 200 -
31-01-2024 11:58:09 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:58:09] "GET /tickets?ticket_status=in_progress HTTP/1.1" 200 -
31-01-2024 11:58:18 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:58:18] "GET /tickets?ticket_status=status HTTP/1.1" 200 -
31-01-2024 11:58:24 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:58:24] "GET /tickets?ticket_status=closed HTTP/1.1" 200 -
31-01-2024 11:58:35 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 11:58:35] "GET /tickets?ticket_status=raised HTTP/1.1" 200 -
31-01-2024 11:59:41 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_handler.py', reloading
31-01-2024 11:59:41 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 11:59:42 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 11:59:42 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 12:00:56 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_controller.py', reloading
31-01-2024 12:00:56 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 12:01:32 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 12:04:02 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 12:05:28 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 12:06:26 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 12:06:34 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:03:19 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:07:08 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:08:07 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:08:09 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 13:08:09 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 13:08:15 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:08:15] "[31m[1mPUT /tickets/Fqw7n/resolve HTTP/1.1[0m" 401 -
31-01-2024 13:08:22 INFO     [employee_login_handler.py:32] Employee with e_id:LLYWi, role:manager logged in
31-01-2024 13:08:22 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:08:22] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 13:08:25 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:08:25] "[31m[1mPUT /tickets/Fqw7n/resolve HTTP/1.1[0m" 403 -
31-01-2024 13:08:44 INFO     [employee_login_handler.py:32] Employee with e_id:SGCxT, role:helpdesk logged in
31-01-2024 13:08:44 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:08:44] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 13:08:49 ERROR    [ticket_operation_handler.py:40] User tried to resolve an already resolved ticket for Ticket Id: Fqw7n
31-01-2024 13:08:49 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:08:49] "[31m[1mPUT /tickets/Fqw7n/resolve HTTP/1.1[0m" 400 -
31-01-2024 13:09:18 INFO     [ticketDAO.py:142] ticket_id: FfKC7 assigned to SGCxT
31-01-2024 13:09:18 INFO     [ticketDAO.py:135] Ticket status changed for ticket_id:FfKC7 to in_progress
31-01-2024 13:09:18 INFO     [ticketDAO.py:113] Message from helpdesk created for ticket_id:FfKC7, message: Our IT team is on its way to solve the issue.
31-01-2024 13:09:18 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:09:18] "PUT /tickets/FfKC7/resolve HTTP/1.1" 200 -
31-01-2024 13:09:41 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:09:41] "[31m[1mPOST /login/employee HTTP/1.1[0m" 401 -
31-01-2024 13:09:47 INFO     [employee_login_handler.py:32] Employee with e_id:LLYWi, role:manager logged in
31-01-2024 13:09:47 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:09:47] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 13:10:02 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:10:02] "GET /tickets/FfKC7 HTTP/1.1" 200 -
31-01-2024 13:10:53 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_controller.py', reloading
31-01-2024 13:10:53 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:10:53 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 13:10:53 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 13:10:57 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:10:57] "GET /tickets/FfKC7 HTTP/1.1" 200 -
31-01-2024 13:13:50 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\ticket\\ticket_controller.py', reloading
31-01-2024 13:13:50 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:13:51 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 13:13:51 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 13:13:54 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:13:54] "GET /tickets/FfKC7 HTTP/1.1" 200 -
31-01-2024 13:18:28 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\message\\messagedao.py', reloading
31-01-2024 13:18:28 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:18:29 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 13:18:29 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 13:20:55 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\config\\queries_config_loader.py', reloading
31-01-2024 13:20:55 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:20:56 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 13:20:56 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 13:20:57 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:20:57] "GET /tickets/FfKC7 HTTP/1.1" 200 -
31-01-2024 13:21:14 INFO     [employee_login_handler.py:32] Employee with e_id:SGCxT, role:helpdesk logged in
31-01-2024 13:21:14 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:21:14] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 13:21:27 ERROR    [ticket_operation_handler.py:70] User tried to resolve an already closed or just raised ticket for Ticket Id: Fqw7n
31-01-2024 13:21:27 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:21:27] "[31m[1mPUT /tickets/Fqw7n/close HTTP/1.1[0m" 400 -
31-01-2024 13:21:34 ERROR    [ticket_operation_handler.py:40] User tried to resolve an already resolved ticket for Ticket Id: FfKC7
31-01-2024 13:21:34 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:21:34] "[31m[1mPUT /tickets/FfKC7/resolve HTTP/1.1[0m" 400 -
31-01-2024 13:21:48 ERROR    [ticket_operation_handler.py:70] User tried to resolve an already closed or just raised ticket for Ticket Id: Fqw7n
31-01-2024 13:21:48 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:21:48] "[31m[1mPUT /tickets/Fqw7n/close HTTP/1.1[0m" 400 -
31-01-2024 13:22:50 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_operation_handler.py', reloading
31-01-2024 13:22:50 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:22:51 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 13:22:51 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 13:22:54 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\handlers\\ticket\\ticket_operation_handler.py', reloading
31-01-2024 13:22:54 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:22:55 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 13:22:55 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 13:23:00 ERROR    [ticket_operation_handler.py:70] User tried to resolve an already closed or just raised ticket for Ticket Id: Fqw7n
31-01-2024 13:23:00 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:23:00] "[31m[1mPUT /tickets/Fqw7n/close HTTP/1.1[0m" 400 -
31-01-2024 13:23:11 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 13:23:11 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 13:23:11 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 13:23:12 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 13:23:12 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 13:23:14 ERROR    [ticket_operation_handler.py:70] User tried to resolve an already closed or just raised ticket for Ticket Id: Fqw7n
31-01-2024 13:23:14 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:23:14] "[31m[1mPUT /tickets/Fqw7n/close HTTP/1.1[0m" 400 -
31-01-2024 13:32:19 INFO     [ticketDAO.py:79] Ticket status changed for ticket_id:FfKC7 to closed
31-01-2024 13:32:19 INFO     [ticketDAO.py:65] Message from helpdesk updated for ticket_id:FfKC7 to Hope your issue got solved.
31-01-2024 13:32:19 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:32:19] "PUT /tickets/FfKC7/close HTTP/1.1" 200 -
31-01-2024 13:34:23 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:34:23] "GET /tickets/FfKC7 HTTP/1.1" 200 -
31-01-2024 13:34:28 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:34:28] "GET /tickets/FfKC7 HTTP/1.1" 200 -
31-01-2024 13:34:49 INFO     [employee_login_handler.py:32] Employee with e_id:LLYWi, role:manager logged in
31-01-2024 13:34:49 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:34:49] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 13:35:02 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:35:02] "PUT /tickets/Fqw7n/message HTTP/1.1" 200 -
31-01-2024 13:35:10 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:35:10] "[33mGET /tickets/FfKC7/message HTTP/1.1[0m" 404 -
31-01-2024 13:35:23 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:35:23] "GET /tickets/Fqw7n/message HTTP/1.1" 200 -
31-01-2024 13:35:51 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:35:51] "[33mPUT /tickets/FfKC7/message HTTP/1.1[0m" 404 -
31-01-2024 13:36:16 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:36:16] "[33mPUT /tickets/FfKC7/message HTTP/1.1[0m" 404 -
31-01-2024 13:36:32 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 13:36:32 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:36:32] "POST /login/customer HTTP/1.1" 200 -
31-01-2024 13:37:04 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:37:04] "GET /tickets?ticket_status=raised HTTP/1.1" 200 -
31-01-2024 13:37:12 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:37:12] "GET /tickets HTTP/1.1" 200 -
31-01-2024 13:37:25 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:37:25] "[35m[1mPOST /tickets/FfKC7/feedback HTTP/1.1[0m" 201 -
31-01-2024 13:37:31 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:37:31] "GET /tickets/FfKC7/feedback HTTP/1.1" 200 -
31-01-2024 13:37:41 INFO     [employee_login_handler.py:32] Employee with e_id:LLYWi, role:manager logged in
31-01-2024 13:37:41 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:37:41] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 13:37:48 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:37:48] "[33mGET /tickets/FfKC7/message HTTP/1.1[0m" 404 -
31-01-2024 13:37:54 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:37:54] "PUT /tickets/FfKC7/message HTTP/1.1" 200 -
31-01-2024 13:37:58 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 13:37:58] "GET /tickets/FfKC7/message HTTP/1.1" 200 -
31-01-2024 15:06:04 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 15:06:04 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 15:06:21 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:06:21] "[33mGET /docs HTTP/1.1[0m" 404 -
31-01-2024 15:06:21 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:06:21] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
31-01-2024 15:06:58 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:06:58] "GET /swagger-ui HTTP/1.1" 200 -
31-01-2024 15:07:00 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:07:00] "GET /api-spec.json HTTP/1.1" 200 -
31-01-2024 15:53:04 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 15:53:04 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 15:54:10 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 15:54:10 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:54:10] "POST /login/customer HTTP/1.1" 200 -
31-01-2024 15:54:32 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 15:54:32 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 15:54:32 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 15:54:33 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 15:54:33 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 15:55:32 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:55:32] "[35m[1mPOST /logout HTTP/1.1[0m" 500 -
31-01-2024 15:56:02 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\users\\user.py', reloading
31-01-2024 15:56:02 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 15:56:03 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 15:56:03 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 15:56:04 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 15:56:04 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 15:56:04 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 15:56:05 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 15:56:05 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 15:56:07 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:56:07] "[35m[1mPOST /logout HTTP/1.1[0m" 500 -
31-01-2024 15:57:18 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\users\\user.py', reloading
31-01-2024 15:57:18 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 15:57:20 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 15:57:20 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 15:57:20 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 15:57:21 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 15:57:21 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 15:57:22 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:57:22] "[35m[1mPOST /logout HTTP/1.1[0m" 500 -
31-01-2024 15:57:52 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\users\\user.py', reloading
31-01-2024 15:57:52 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 15:57:53 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 15:57:53 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 15:57:55 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 15:57:55 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 15:57:55 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 15:57:56 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 15:57:56 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 15:57:57 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:57:57] "[35m[1mPOST /logout HTTP/1.1[0m" 500 -
31-01-2024 15:58:34 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\users\\user.py', reloading
31-01-2024 15:58:34 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 15:58:35 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 15:58:35 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 15:58:37 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 15:58:37 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 15:58:37 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 15:58:38 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 15:58:38 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 15:58:39 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 15:58:39] "[35m[1mPOST /logout HTTP/1.1[0m" 500 -
31-01-2024 16:00:45 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 16:00:45 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 16:00:45 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:00:46 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:00:46 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:00:59 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\users\\user.py', reloading
31-01-2024 16:00:59 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:01:00 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:01:00 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:01:03 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:01:03] "[35m[1mPOST /logout HTTP/1.1[0m" 500 -
31-01-2024 16:01:31 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 16:01:31 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 16:01:31 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:01:32 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:01:32 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:01:33 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:01:33] "[35m[1mPOST /logout HTTP/1.1[0m" 500 -
31-01-2024 16:01:59 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\app.py', reloading
31-01-2024 16:01:59 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:02:00 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:02:00 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:02:03 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 16:02:03 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 16:02:03 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:02:04 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:02:04 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:02:06 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:02:06] "[35m[1mPOST /logout HTTP/1.1[0m" 500 -
31-01-2024 16:02:14 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\app.py', reloading
31-01-2024 16:02:14 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:02:15 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:02:15 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:02:16 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:02:16] "[35m[1mPOST /logout HTTP/1.1[0m" 500 -
31-01-2024 16:02:28 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\app.py', reloading
31-01-2024 16:02:28 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:02:29 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:02:29 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:02:38 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\app.py', reloading
31-01-2024 16:02:38 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:02:38 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:02:38 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:03:18 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\users\\user.py', reloading
31-01-2024 16:03:18 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:03:19 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:03:19 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:03:21 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:03:21] "[33mPOST /logout HTTP/1.1[0m" 404 -
31-01-2024 16:03:26 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\users\\user.py', reloading
31-01-2024 16:03:26 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:03:26 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:03:26 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:03:37 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\users\\user.py', reloading
31-01-2024 16:03:39 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 16:03:39 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 16:03:39 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:03:40 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:03:40 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:03:41 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:03:41] "POST /logout HTTP/1.1" 200 -
31-01-2024 16:03:59 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:03:59] "[31m[1mGET /tickets HTTP/1.1[0m" 401 -
31-01-2024 16:04:23 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\app.py', reloading
31-01-2024 16:04:23 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:04:24 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:04:24 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:06:24 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 16:06:24 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 16:06:24 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:06:25 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:06:25 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:34:34 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 16:34:34 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 16:34:34 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 16:34:35 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 16:34:35 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 16:35:02 INFO     [customer_signup_handler.py:35] New Customer signup with name:Mr. dby and email:dby@gmail.com
31-01-2024 16:35:02 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:35:02] "[35m[1mPOST /signup HTTP/1.1[0m" 201 -
31-01-2024 16:58:11 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:58:11] "[31m[1mPOST /tickets HTTP/1.1[0m" 401 -
31-01-2024 16:58:17 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 16:58:17 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:58:17] "POST /login/customer HTTP/1.1" 200 -
31-01-2024 16:58:20 INFO     [ticketDAO.py:32] New ticket raised with ticket_id:DrsDf, title:Need Help ASAP Router. by customer:RPfe5
31-01-2024 16:58:20 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:58:20] "[35m[1mPOST /tickets HTTP/1.1[0m" 201 -
31-01-2024 16:59:06 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:59:06] "GET /tickets/DrsDf HTTP/1.1" 200 -
31-01-2024 16:59:14 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:59:14] "GET /tickets HTTP/1.1" 200 -
31-01-2024 16:59:20 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 16:59:20] "GET /tickets?ticket_status=raised HTTP/1.1" 200 -
31-01-2024 17:00:17 INFO     [employee_login_handler.py:32] Employee with e_id:LLYWi, role:manager logged in
31-01-2024 17:00:17 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:00:17] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 17:00:22 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:00:22] "GET /tickets/DrsDf HTTP/1.1" 200 -
31-01-2024 17:01:10 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:01:10] "[31m[1mPUT /tickets/DrsDf/resolve HTTP/1.1[0m" 403 -
31-01-2024 17:01:21 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:01:21] "GET /tickets?ticket_status=raised HTTP/1.1" 200 -
31-01-2024 17:01:32 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:01:32] "[31m[1mPUT /tickets/DrsDf/resolve HTTP/1.1[0m" 403 -
31-01-2024 17:01:39 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:01:39] "GET /tickets/DrsDf HTTP/1.1" 200 -
31-01-2024 17:01:58 INFO     [employee_login_handler.py:32] Employee with e_id:SGCxT, role:helpdesk logged in
31-01-2024 17:01:58 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:01:58] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 17:02:02 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:02:02] "GET /tickets/DrsDf HTTP/1.1" 200 -
31-01-2024 17:02:14 INFO     [ticketDAO.py:85] ticket_id: DrsDf assigned to SGCxT
31-01-2024 17:02:14 INFO     [ticketDAO.py:78] Ticket status changed for ticket_id:DrsDf to in_progress
31-01-2024 17:02:14 INFO     [ticketDAO.py:56] Message from helpdesk created for ticket_id:DrsDf, message: Our IT team is on its way to solve the issue.
31-01-2024 17:02:14 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:02:14] "PUT /tickets/DrsDf/resolve HTTP/1.1" 200 -
31-01-2024 17:02:20 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:02:20] "GET /tickets/DrsDf HTTP/1.1" 200 -
31-01-2024 17:05:58 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\controllers\\authentication\\customer\\customer_login_controller.py', reloading
31-01-2024 17:05:58 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 17:05:59 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 17:05:59 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 17:06:07 INFO     [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
31-01-2024 17:06:07 INFO     [_internal.py:96] [33mPress CTRL+C to quit[0m
31-01-2024 17:06:07 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 17:06:08 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 17:06:08 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 17:18:17 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\resources\\users\\user.py', reloading
31-01-2024 17:18:17 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 17:18:20 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 17:18:20 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 17:25:42 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\DBUtils\\connection\\database_connection.py', reloading
31-01-2024 17:25:42 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 17:25:43 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 17:25:43 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 17:25:49 INFO     [customer_login_handler.py:34] Customer with c_id:RPfe5 logged in
31-01-2024 17:25:49 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:25:49] "POST /login/customer HTTP/1.1" 200 -
31-01-2024 17:26:07 INFO     [ticketDAO.py:32] New ticket raised with ticket_id:TnSBW, title:Need Help ASAP PC. by customer:RPfe5
31-01-2024 17:26:07 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:26:07] "[35m[1mPOST /tickets HTTP/1.1[0m" 201 -
31-01-2024 17:26:59 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:26:59] "GET /tickets/TnSBW HTTP/1.1" 200 -
31-01-2024 17:27:20 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:27:20] "GET /tickets?ticket_status=raised HTTP/1.1" 200 -
31-01-2024 17:27:31 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:27:31] "GET /tickets HTTP/1.1" 200 -
31-01-2024 17:27:39 INFO     [employee_login_handler.py:32] Employee with e_id:SGCxT, role:helpdesk logged in
31-01-2024 17:27:39 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:27:39] "POST /login/employee HTTP/1.1" 200 -
31-01-2024 17:27:57 INFO     [ticketDAO.py:85] ticket_id: TnSBW assigned to SGCxT
31-01-2024 17:27:57 INFO     [ticketDAO.py:78] Ticket status changed for ticket_id:TnSBW to in_progress
31-01-2024 17:27:57 INFO     [ticketDAO.py:56] Message from helpdesk created for ticket_id:TnSBW, message: Our IT team is on its way to solve the issue.
31-01-2024 17:27:57 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:27:57] "PUT /tickets/TnSBW/resolve HTTP/1.1" 200 -
31-01-2024 17:28:03 INFO     [_internal.py:96] 127.0.0.1 - - [31/Jan/2024 17:28:03] "GET /tickets/TnSBW HTTP/1.1" 200 -
31-01-2024 17:29:00 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\app.py', reloading
31-01-2024 17:29:00 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 17:29:01 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 17:29:01 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
31-01-2024 18:25:19 INFO     [_internal.py:96]  * Detected change in 'C:\\Users\\mbhatnagar\\PycharmProjects\\CSM\\src\\app.py', reloading
31-01-2024 18:25:19 INFO     [_internal.py:96]  * Restarting with stat
31-01-2024 18:25:22 WARNING  [_internal.py:96]  * Debugger is active!
31-01-2024 18:25:22 INFO     [_internal.py:96]  * Debugger PIN: 436-338-038
